/**
 * Icon pipeline note
 * ------------------
 * The ONLY source of the Weport app icon is:
 *
 *   assets/branding/weport-icon.jpg
 *
 * All sizes / ICO / tray / window icons are generated at compile time by
 * `src-tauri/build.rs` from that file. There is no hand-drawn or
 * procedural mark anymore.
 *
 * Usage:
 *   cargo build --manifest-path src-tauri/Cargo.toml
 *   # writes src-tauri/icons/* and OUT_DIR embeds
 *
 * To change the brand mark: replace assets/branding/weport-icon.jpg, then rebuild.
 */
console.log('Icons are generated by src-tauri/build.rs from assets/branding/weport-icon.jpg')
console.log('Run: cargo build --manifest-path src-tauri/Cargo.toml')
process.exit(0)
